"""add user and breeder tables

Revision ID: 10dafe982aea
Revises: 64452e386f4a
Create Date: 2025-08-18 10:34:41.230158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10dafe982aea'
down_revision: Union[str, Sequence[str], None] = '64452e386f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breeders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breeders_name'), 'breeders', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('breeder_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['breeder_id'], ['breeders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('plant_measurements', 'variety')
    op.add_column('plants', sa.Column('breeder_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'plants', 'breeders', ['breeder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plants', type_='foreignkey')
    op.drop_column('plants', 'breeder_id')
    op.add_column('plant_measurements', sa.Column('variety', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_breeders_name'), table_name='breeders')
    op.drop_table('breeders')
    # ### end Alembic commands ###
