"""Update PlantMeasurement schema

Revision ID: 64452e386f4a
Revises: be2c6f352e44
Create Date: 2025-08-06 23:05:24.812156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64452e386f4a'
down_revision: Union[str, Sequence[str], None] = 'be2c6f352e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('biomass', sa.Float(), nullable=True),
    sa.Column('canopy_density', sa.Float(), nullable=True),
    sa.Column('ripe', sa.Integer(), nullable=True),
    sa.Column('part_ripe', sa.Integer(), nullable=True),
    sa.Column('unripe', sa.Integer(), nullable=True),
    sa.Column('flower', sa.Integer(), nullable=True),
    sa.Column('fruit_width', sa.Float(), nullable=True),
    sa.Column('fruit_height', sa.Float(), nullable=True),
    sa.Column('mass', sa.Float(), nullable=True),
    sa.Column('yield_per_plant', sa.Float(), nullable=True),
    sa.Column('crop_composition', sa.Float(), nullable=True),
    sa.Column('plant_height', sa.Float(), nullable=True),
    sa.Column('exg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.plant_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id', 'date', name='uix_plant_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant_measurements')
    # ### end Alembic commands ###
